import facebookHelper from '../../../src/facebook/helper.js'

describe.only('facebook-helper', function() {
  return it("get friends list", function(done) {
    var token, userId;
    userId = "100000233810027";
    token = "EAACEdEose0cBAGPqBhJXUtZA3ODNE6GLa5Qjl173vrYu40a5Nntj6XQjgIKimOwkvQUsuXCQIOVAsjheeUPkMiUgyLJyPMZA25vk9f2U2wRB5e4vzUFv21WJdZCmaYvZBaXWZA7EOUgyWUGEwlDNqFZB9BiiA7YTZAj6dY4WL5VcNnAuM9D85zyE7tWCcUJmlYZD";
    return facebookHelper.getFriends(userId, token, function(error, friends) {
      console.log("friends", friends);
      (friends !== void 0).should.be["true"];
      friends.should.be.Array;
      friends[0].should.have.keys("name", "id");
      return done();
    });
  });
});

// ---
// generated by coffee-script 1.9.2
